import treeQuadrature.splits
import treeQuadrature.containerIntegration
import treeQuadrature.exampleDistributions
import treeQuadrature.utils
import treeQuadrature.visualisation
import treeQuadrature.selection

from .container import Container