import numpy as np
from typing import Callable, Optional, Dict

from .base_class import ContainerIntegral
from ..container import Container
from ..samplers import Sampler, UniformSampler


defaultSampler = UniformSampler()


class RandomIntegral(ContainerIntegral):
    """
    Monte Carlo integrator:
    redraw samples, and estimate integrand
    by the a constant value

    Parameters
    ----------
    n_samples : int
        number of samples to be redrawn for evaluating the integral.
        Default : 10
    eval : function
        Should take a np.ndarray (samples of integrand)
        and return a float (aggregated value).
        Default is mean
    error_estimate : function
        must be provided when eval is not mean nor median.
        Used to obtain an estimate of the uncertainty
    sampler : Sampler
        The sampler used to draw samples in the container
        Default is UniformSampler
    """

    def __init__(
        self,
        n_samples: int = 10,
        eval: Callable = np.mean,
        error_estimate: Optional[Callable] = None,
        sampler: Sampler = defaultSampler,
    ) -> None:
        self.n_samples = n_samples
        self.name = "RandomIntegral"
        self.eval = eval
        self.error_estimate = error_estimate
        self.sampler = sampler

    def containerIntegral(
        self, container: Container, f: Callable,
        return_std: bool = False,
        return_samples: bool = False,
    ):

        xs, ys = self.sampler.rvs(self.n_samples,
                                  container.mins, container.maxs,
                                  f)
        self._sample_check(xs, ys, container.D)

        # for tracking num function evaluations
        container.add(xs, ys)  
        # ignore previous samples in the container
        # which will give skewed estimates

        y = self.eval(ys)
        integral_estimate = y * container.volume
        results = {"integral": integral_estimate}

        if return_std:
            std = self.estimate_error(ys)
            results["std"] = std * container.volume
        if return_samples:
            results["samples"] = (xs, ys)

        return results

    def estimate_error(self, samples: np.ndarray):
        if len(samples) < 2:
            return 0

        if self.eval == np.mean:
            std = np.sqrt(np.var(samples) / len(samples))
        elif self.eval == np.median:
            median_value = np.median(samples)
            mad = np.median(np.abs(samples - median_value))
            std = mad / np.sqrt(len(samples))
        elif self.error_estimate is not None:
            std = self.error_estimate(samples)
        else:
            raise ValueError(
                "evaluation method is not mean nor median, "
                "must specify 'error_estimate'"
            )

        return std
    
    def _sample_check(self, xs, ys, dim,
                      sample_size: int=None):
        """ check samples are correct """
        if xs.shape[0] != ys.shape[0]:
            raise ValueError(
                "the shape of xs and ys generated by sampler does not match"
            )
        if xs.shape[1] != dim:
            raise ValueError(
                "the dimension of xs does not match required dimension"
            )
        if sample_size is not None: 
            expected_sample_size = sample_size
        else:
            expected_sample_size = self.n_samples
        if xs.shape[0] != expected_sample_size:
            raise RuntimeError(
                "Too many samples! "
                f"sampler.rvs generated {xs.shape[0]} samples"
                f"while expecting {self.n_samples}"
            )

class ProgressiveRandomIntegral(RandomIntegral):
    """
    Monte Carlo integrator with progressive sampling:
    samples are stored within each container and reused across calls,
    allowing for additional samples to be drawn progressively in each call.
    """
    def containerIntegral(
        self, container: Container, f: Callable,
        additional_samples: int = 10,
        return_std: bool = False,
        return_samples: bool = False,
    ) -> Dict[str, float]:
        """
        Parameters
        ----------
        additional_samples : int
            Number of additional samples to be drawn
            if the container has previous samples.
            Default : 10
        """
        first_evaluation = not hasattr(container, "evaluation_samples")

        if first_evaluation:
            sample_size = self.n_samples
        else:
            sample_size = additional_samples

        new_xs, new_ys = self.sampler.rvs(
            sample_size,
            container.mins, container.maxs,
            f
        )

        self._sample_check(new_xs, new_ys, container.D, sample_size)

        # Initialise or extend evaluation_samples in the container
        if first_evaluation:
            container.evaluation_samples = (new_xs, new_ys)
        else:
            # Concatenate new samples to the existing ones
            stored_xs, stored_ys = container.evaluation_samples
            container.evaluation_samples = (
                np.vstack([stored_xs, new_xs]),
                np.concatenate([stored_ys, new_ys])
            )

        # Retrieve all accumulated samples for this container
        xs, ys = container.evaluation_samples

        # Evaluate integral using all accumulated samples
        y = self.eval(ys)
        integral_estimate = y * container.volume
        results = {"integral": integral_estimate}
        results['sample_size'] = ys.shape[0]

        if return_std:
            std = self.estimate_error(ys)
            results["std"] = std * container.volume
        if return_samples:
            results["samples"] = (xs, ys)

        return results
